name: Deploy to InfinityFree

on:
  push:
    branches:
      - main  # Se a sua branch principal se chamar 'master', mude aqui de 'main' para 'master'

jobs:
  web-deploy:
    name: 🎉 Deploy
    runs-on: ubuntu-latest
    steps:
    - name: 🚚 Get latest code
      uses: actions/checkout@v4

    - name: 📂 Sync files to InfinityFree
      uses: SamKirkland/FTP-Deploy-Action@v4.3.5
      with:
        server: ftpupload.net
        username: ${{ secrets.FTP_USERNAME }}
        password: ${{ secrets.FTP_PASSWORD }}

        local-dir: ./                  # Envia tudo o que está na raiz do repositório
        server-dir: ./htdocs/          # Envia direto para a pasta pública do InfinityFree
        dangerous-clean-slate: false   # Mantém arquivos extras que já estejam no servidor
